#!/bin/bash
# 设置可执行权限： chmod +x CleanerRunScript/run_raha_baran/run.sh
# 运行方式：./CleanerRunScript/run_raha_baran/run.sh

# 定义命令列表，每个命令用于不同的数据集
commands=(
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/1_hospital/noise_with_correct_primary_key/dirty_mixed_0.25/dirty_hospitals_mix_0.25.csv --clean_path Data/1_hospital/clean_index.csv --task_name 1_hospital_nwcpk_025 --output_path results/raha_baran/nwcpk --index_attribute index --mse_attributes Score"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/1_hospital/noise_with_correct_primary_key/dirty_mixed_0.5/dirty_hospitals_mix_0.5.csv --clean_path Data/1_hospital/clean_index.csv --task_name 1_hospital_nwcpk_050 --output_path results/raha_baran/nwcpk --index_attribute index --mse_attributes Score"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/1_hospital/noise_with_correct_primary_key/dirty_mixed_0.75/dirty_hospitals_mix_0.75.csv --clean_path Data/1_hospital/clean_index.csv --task_name 1_hospital_nwcpk_075 --output_path results/raha_baran/nwcpk --index_attribute index --mse_attributes Score"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/1_hospital/noise_with_correct_primary_key/dirty_mixed_1/dirty_hospitals_mix_1.csv --clean_path Data/1_hospital/clean_index.csv --task_name 1_hospital_nwcpk_100 --output_path results/raha_baran/nwcpk --index_attribute index --mse_attributes Score"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/1_hospital/noise_with_correct_primary_key/dirty_mixed_1.25/dirty_hospitals_mix_1.25.csv --clean_path Data/1_hospital/clean_index.csv --task_name 1_hospital_nwcpk_125 --output_path results/raha_baran/nwcpk --index_attribute index --mse_attributes Score"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/1_hospital/noise_with_correct_primary_key/dirty_mixed_1.5/dirty_hospitals_mix_1.5.csv --clean_path Data/1_hospital/clean_index.csv --task_name 1_hospital_nwcpk_150 --output_path results/raha_baran/nwcpk --index_attribute index --mse_attributes Score"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/1_hospital/noise_with_correct_primary_key/dirty_mixed_1.75/dirty_hospitals_mix_1.75.csv --clean_path Data/1_hospital/clean_index.csv --task_name 1_hospital_nwcpk_175 --output_path results/raha_baran/nwcpk --index_attribute index --mse_attributes Score"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/1_hospital/noise_with_correct_primary_key/dirty_mixed_2/dirty_hospitals_mix_2.csv --clean_path Data/1_hospital/clean_index.csv --task_name 1_hospital_nwcpk_200 --output_path results/raha_baran/nwcpk --index_attribute index --mse_attributes Score"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/2_flights/noise_with_correct_primary_key/dirty_mixed_0.25/dirty_flights_mix_0.25.csv --clean_path Data/2_flights/clean_index.csv --task_name 2_flights_nwcpk_025 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/2_flights/noise_with_correct_primary_key/dirty_mixed_0.5/dirty_flights_mix_0.5.csv --clean_path Data/2_flights/clean_index.csv --task_name 2_flights_nwcpk_050 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/2_flights/noise_with_correct_primary_key/dirty_mixed_0.75/dirty_flights_mix_0.75.csv --clean_path Data/2_flights/clean_index.csv --task_name 2_flights_nwcpk_075 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/2_flights/noise_with_correct_primary_key/dirty_mixed_1/dirty_flights_mix_1.csv --clean_path Data/2_flights/clean_index.csv --task_name 2_flights_nwcpk_100 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/2_flights/noise_with_correct_primary_key/dirty_mixed_1.25/dirty_flights_mix_1.25.csv --clean_path Data/2_flights/clean_index.csv --task_name 2_flights_nwcpk_125 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/2_flights/noise_with_correct_primary_key/dirty_mixed_1.5/dirty_flights_mix_1.5.csv --clean_path Data/2_flights/clean_index.csv --task_name 2_flights_nwcpk_150 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/2_flights/noise_with_correct_primary_key/dirty_mixed_1.75/dirty_flights_mix_1.75.csv --clean_path Data/2_flights/clean_index.csv --task_name 2_flights_nwcpk_175 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/2_flights/noise_with_correct_primary_key/dirty_mixed_2/dirty_flights_mix_2.csv --clean_path Data/2_flights/clean_index.csv --task_name 2_flights_nwcpk_200 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/3_beers/noise_with_correct_primary_key/dirty_mixed_0.25/dirty_beers_mix_0.25.csv --clean_path Data/3_beers/clean.csv --task_name 3_beers_nwcpk_025 --output_path results/raha_baran/nwcpk --index_attribute id --mse_attributes abv ibu"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/3_beers/noise_with_correct_primary_key/dirty_mixed_0.5/dirty_beers_mix_0.5.csv --clean_path Data/3_beers/clean.csv --task_name 3_beers_nwcpk_050 --output_path results/raha_baran/nwcpk --index_attribute id --mse_attributes abv ibu"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/3_beers/noise_with_correct_primary_key/dirty_mixed_0.75/dirty_beers_mix_0.75.csv --clean_path Data/3_beers/clean.csv --task_name 3_beers_nwcpk_075 --output_path results/raha_baran/nwcpk --index_attribute id --mse_attributes abv ibu"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/3_beers/noise_with_correct_primary_key/dirty_mixed_1/dirty_beers_mix_1.csv --clean_path Data/3_beers/clean.csv --task_name 3_beers_nwcpk_100 --output_path results/raha_baran/nwcpk --index_attribute id --mse_attributes abv ibu"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/3_beers/noise_with_correct_primary_key/dirty_mixed_1.25/dirty_beers_mix_1.25.csv --clean_path Data/3_beers/clean.csv --task_name 3_beers_nwcpk_125 --output_path results/raha_baran/nwcpk --index_attribute id --mse_attributes abv ibu"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/3_beers/noise_with_correct_primary_key/dirty_mixed_1.5/dirty_beers_mix_1.5.csv --clean_path Data/3_beers/clean.csv --task_name 3_beers_nwcpk_150 --output_path results/raha_baran/nwcpk --index_attribute id --mse_attributes abv ibu"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/3_beers/noise_with_correct_primary_key/dirty_mixed_1.75/dirty_beers_mix_1.75.csv --clean_path Data/3_beers/clean.csv --task_name 3_beers_nwcpk_175 --output_path results/raha_baran/nwcpk --index_attribute id --mse_attributes abv ibu"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/3_beers/noise_with_correct_primary_key/dirty_mixed_2/dirty_beers_mix_2.csv --clean_path Data/3_beers/clean.csv --task_name 3_beers_nwcpk_200 --output_path results/raha_baran/nwcpk --index_attribute id --mse_attributes abv ibu"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/4_rayyan/noise_with_correct_primary_key/rayyan_0.25/dirty_rayyan_mix_0.25.csv --clean_path Data/4_rayyan/clean_index.csv --task_name 4_rayyan_nwcpk_025 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/4_rayyan/noise_with_correct_primary_key/rayyan_0.5/dirty_rayyan_mix_0.5.csv --clean_path Data/4_rayyan/clean_index.csv --task_name 4_rayyan_nwcpk_050 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/4_rayyan/noise_with_correct_primary_key/rayyan_0.75/dirty_rayyan_mix_0.75.csv --clean_path Data/4_rayyan/clean_index.csv --task_name 4_rayyan_nwcpk_075 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/4_rayyan/noise_with_correct_primary_key/rayyan_1/dirty_rayyan_mix_1.csv --clean_path Data/4_rayyan/clean_index.csv --task_name 4_rayyan_nwcpk_100 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/4_rayyan/noise_with_correct_primary_key/rayyan_1.25/dirty_rayyan_mix_1.25.csv --clean_path Data/4_rayyan/clean_index.csv --task_name 4_rayyan_nwcpk_125 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/4_rayyan/noise_with_correct_primary_key/rayyan_1.5/dirty_rayyan_mix_1.5.csv --clean_path Data/4_rayyan/clean_index.csv --task_name 4_rayyan_nwcpk_150 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/4_rayyan/noise_with_correct_primary_key/rayyan_1.75/dirty_rayyan_mix_1.75.csv --clean_path Data/4_rayyan/clean_index.csv --task_name 4_rayyan_nwcpk_175 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/4_rayyan/noise_with_correct_primary_key/rayyan_2/dirty_rayyan_mix_2.csv --clean_path Data/4_rayyan/clean_index.csv --task_name 4_rayyan_nwcpk_200 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_20k/noise_with_correct_primary_key/dirty_mix_0.25/dirty_tax_mix_0.25.csv --clean_path Data/5_tax/tax_20k/tax_20k_clean_id.csv --task_name 5_tax_20k_nwcpk_025 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_20k/noise_with_correct_primary_key/dirty_mix_0.5/dirty_tax_mix_0.5.csv --clean_path Data/5_tax/tax_20k/tax_20k_clean_id.csv --task_name 5_tax_20k_nwcpk_050 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_20k/noise_with_correct_primary_key/dirty_mix_0.75/dirty_tax_mix_0.75.csv --clean_path Data/5_tax/tax_20k/tax_20k_clean_id.csv --task_name 5_tax_20k_nwcpk_075 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_20k/noise_with_correct_primary_key/dirty_mix_1/dirty_tax_mix_1.csv --clean_path Data/5_tax/tax_20k/tax_20k_clean_id.csv --task_name 5_tax_20k_nwcpk_100 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_20k/noise_with_correct_primary_key/dirty_mix_1.25/dirty_tax_mix_1.25.csv --clean_path Data/5_tax/tax_20k/tax_20k_clean_id.csv --task_name 5_tax_20k_nwcpk_125 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_20k/noise_with_correct_primary_key/dirty_mix_1.5/dirty_tax_mix_1.5.csv --clean_path Data/5_tax/tax_20k/tax_20k_clean_id.csv --task_name 5_tax_20k_nwcpk_150 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_20k/noise_with_correct_primary_key/dirty_mix_1.75/dirty_tax_mix_1.75.csv --clean_path Data/5_tax/tax_20k/tax_20k_clean_id.csv --task_name 5_tax_20k_nwcpk_175 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_20k/noise_with_correct_primary_key/dirty_mix_2/dirty_tax_mix_2.csv --clean_path Data/5_tax/tax_20k/tax_20k_clean_id.csv --task_name 5_tax_20k_nwcpk_200 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_50k/noise_with_correct_primary_key/dirty_mix_0.25/dirty_tax_mix_0.25.csv --clean_path Data/5_tax/tax_50k/tax_50k_clean_id.csv --task_name 5_tax_50k_nwcpk_025 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_50k/noise_with_correct_primary_key/dirty_mix_0.5/dirty_tax_mix_0.5.csv --clean_path Data/5_tax/tax_50k/tax_50k_clean_id.csv --task_name 5_tax_50k_nwcpk_050 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_50k/noise_with_correct_primary_key/dirty_mix_0.75/dirty_tax_mix_0.75.csv --clean_path Data/5_tax/tax_50k/tax_50k_clean_id.csv --task_name 5_tax_50k_nwcpk_075 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_50k/noise_with_correct_primary_key/dirty_mix_1/dirty_tax_mix_1.csv --clean_path Data/5_tax/tax_50k/tax_50k_clean_id.csv --task_name 5_tax_50k_nwcpk_100 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_50k/noise_with_correct_primary_key/dirty_mix_1.25/dirty_tax_mix_1.25.csv --clean_path Data/5_tax/tax_50k/tax_50k_clean_id.csv --task_name 5_tax_50k_nwcpk_125 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_50k/noise_with_correct_primary_key/dirty_mix_1.5/dirty_tax_mix_1.5.csv --clean_path Data/5_tax/tax_50k/tax_50k_clean_id.csv --task_name 5_tax_50k_nwcpk_150 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_50k/noise_with_correct_primary_key/dirty_mix_1.75/dirty_tax_mix_1.75.csv --clean_path Data/5_tax/tax_50k/tax_50k_clean_id.csv --task_name 5_tax_50k_nwcpk_175 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_50k/noise_with_correct_primary_key/dirty_mix_2/dirty_tax_mix_2.csv --clean_path Data/5_tax/tax_50k/tax_50k_clean_id.csv --task_name 5_tax_50k_nwcpk_200 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_200k/noise_with_correct_primary_key/dirty_mix_0.25/dirty_tax_mix_0.25.csv --clean_path Data/5_tax/tax_200k/tax_200k_clean_id.csv --task_name 5_tax_200k_nwcpk_025 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_200k/noise_with_correct_primary_key/dirty_mix_0.5/dirty_tax_mix_0.5.csv --clean_path Data/5_tax/tax_200k/tax_200k_clean_id.csv --task_name 5_tax_200k_nwcpk_050 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_200k/noise_with_correct_primary_key/dirty_mix_0.75/dirty_tax_mix_0.75.csv --clean_path Data/5_tax/tax_200k/tax_200k_clean_id.csv --task_name 5_tax_200k_nwcpk_075 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_200k/noise_with_correct_primary_key/dirty_mix_1/dirty_tax_mix_1.csv --clean_path Data/5_tax/tax_200k/tax_200k_clean_id.csv --task_name 5_tax_200k_nwcpk_100 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_200k/noise_with_correct_primary_key/dirty_mix_1.25/dirty_tax_mix_1.25.csv --clean_path Data/5_tax/tax_200k/tax_200k_clean_id.csv --task_name 5_tax_200k_nwcpk_125 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_200k/noise_with_correct_primary_key/dirty_mix_1.5/dirty_tax_mix_1.5.csv --clean_path Data/5_tax/tax_200k/tax_200k_clean_id.csv --task_name 5_tax_200k_nwcpk_150 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_200k/noise_with_correct_primary_key/dirty_mix_1.75/dirty_tax_mix_1.75.csv --clean_path Data/5_tax/tax_200k/tax_200k_clean_id.csv --task_name 5_tax_200k_nwcpk_175 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/5_tax/tax_200k/noise_with_correct_primary_key/dirty_mix_2/dirty_tax_mix_2.csv --clean_path Data/5_tax/tax_200k/tax_200k_clean_id.csv --task_name 5_tax_200k_nwcpk_200 --output_path results/raha_baran/nwcpk --index_attribute tno --mse_attributes rate"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/6_soccer/noise_with_primary_key/dirty_mixed_0.25/dirty_soccer_mix_0.25.csv --clean_path Data/6_soccer/clean_index.csv --task_name 6_soccer_nwcpk_025 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/6_soccer/noise_with_primary_key/dirty_mixed_0.5/dirty_soccer_mix_0.5.csv --clean_path Data/6_soccer/clean_index.csv --task_name 6_soccer_nwcpk_050 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/6_soccer/noise_with_primary_key/dirty_mixed_0.75/dirty_soccer_mix_0.75.csv --clean_path Data/6_soccer/clean_index.csv --task_name 6_soccer_nwcpk_075 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/6_soccer/noise_with_primary_key/dirty_mixed_1/dirty_soccer_mix_1.csv --clean_path Data/6_soccer/clean_index.csv --task_name 6_soccer_nwcpk_100 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/6_soccer/noise_with_primary_key/dirty_mixed_1.25/dirty_soccer_mix_1.25.csv --clean_path Data/6_soccer/clean_index.csv --task_name 6_soccer_nwcpk_125 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/6_soccer/noise_with_primary_key/dirty_mixed_1.5/dirty_soccer_mix_1.5.csv --clean_path Data/6_soccer/clean_index.csv --task_name 6_soccer_nwcpk_150 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/6_soccer/noise_with_primary_key/dirty_mixed_1.75/dirty_soccer_mix_1.75.csv --clean_path Data/6_soccer/clean_index.csv --task_name 6_soccer_nwcpk_175 --output_path results/raha_baran/nwcpk --index_attribute index"
    "python3 CleanerRunScript/run_raha_baran/repair_with_raha.py --dirty_path Data/6_soccer/noise_with_primary_key/dirty_mixed_2/dirty_soccer_mix_2.csv --clean_path Data/6_soccer/clean_index.csv --task_name 6_soccer_nwcpk_200 --output_path results/raha_baran/nwcpk --index_attribute index"
)


# 定义日志文件名列表
log_files=(
    "logs/raha_baran_nwcpk/1_hospital_raha_baran_nwcpk_025.log"
    "logs/raha_baran_nwcpk/1_hospital_raha_baran_nwcpk_050.log"
    "logs/raha_baran_nwcpk/1_hospital_raha_baran_nwcpk_075.log"
    "logs/raha_baran_nwcpk/1_hospital_raha_baran_nwcpk_100.log"
    "logs/raha_baran_nwcpk/1_hospital_raha_baran_nwcpk_125.log"
    "logs/raha_baran_nwcpk/1_hospital_raha_baran_nwcpk_150.log"
    "logs/raha_baran_nwcpk/1_hospital_raha_baran_nwcpk_175.log"
    "logs/raha_baran_nwcpk/1_hospital_raha_baran_nwcpk_200.log"
    "logs/raha_baran_nwcpk/2_flights_raha_baran_nwcpk_025.log"
    "logs/raha_baran_nwcpk/2_flights_raha_baran_nwcpk_050.log"
    "logs/raha_baran_nwcpk/2_flights_raha_baran_nwcpk_075.log"
    "logs/raha_baran_nwcpk/2_flights_raha_baran_nwcpk_100.log"
    "logs/raha_baran_nwcpk/2_flights_raha_baran_nwcpk_125.log"
    "logs/raha_baran_nwcpk/2_flights_raha_baran_nwcpk_150.log"
    "logs/raha_baran_nwcpk/2_flights_raha_baran_nwcpk_175.log"
    "logs/raha_baran_nwcpk/2_flights_raha_baran_nwcpk_200.log"
    "logs/raha_baran_nwcpk/3_beers_raha_baran_nwcpk_025.log"
    "logs/raha_baran_nwcpk/3_beers_raha_baran_nwcpk_050.log"
    "logs/raha_baran_nwcpk/3_beers_raha_baran_nwcpk_075.log"
    "logs/raha_baran_nwcpk/3_beers_raha_baran_nwcpk_100.log"
    "logs/raha_baran_nwcpk/3_beers_raha_baran_nwcpk_125.log"
    "logs/raha_baran_nwcpk/3_beers_raha_baran_nwcpk_150.log"
    "logs/raha_baran_nwcpk/3_beers_raha_baran_nwcpk_175.log"
    "logs/raha_baran_nwcpk/3_beers_raha_baran_nwcpk_200.log"
    "logs/raha_baran_nwcpk/4_rayyan_raha_baran_nwcpk_025.log"
    "logs/raha_baran_nwcpk/4_rayyan_raha_baran_nwcpk_050.log"
    "logs/raha_baran_nwcpk/4_rayyan_raha_baran_nwcpk_075.log"
    "logs/raha_baran_nwcpk/4_rayyan_raha_baran_nwcpk_100.log"
    "logs/raha_baran_nwcpk/4_rayyan_raha_baran_nwcpk_125.log"
    "logs/raha_baran_nwcpk/4_rayyan_raha_baran_nwcpk_150.log"
    "logs/raha_baran_nwcpk/4_rayyan_raha_baran_nwcpk_175.log"
    "logs/raha_baran_nwcpk/4_rayyan_raha_baran_nwcpk_200.log"
    "logs/raha_baran_nwcpk/5_tax_20k_raha_baran_nwcpk_025.log"
    "logs/raha_baran_nwcpk/5_tax_20k_raha_baran_nwcpk_050.log"
    "logs/raha_baran_nwcpk/5_tax_20k_raha_baran_nwcpk_075.log"
    "logs/raha_baran_nwcpk/5_tax_20k_raha_baran_nwcpk_100.log"
    "logs/raha_baran_nwcpk/5_tax_20k_raha_baran_nwcpk_125.log"
    "logs/raha_baran_nwcpk/5_tax_20k_raha_baran_nwcpk_150.log"
    "logs/raha_baran_nwcpk/5_tax_20k_raha_baran_nwcpk_175.log"
    "logs/raha_baran_nwcpk/5_tax_20k_raha_baran_nwcpk_200.log"
    "logs/raha_baran_nwcpk/5_tax_50k_raha_baran_nwcpk_025.log"
    "logs/raha_baran_nwcpk/5_tax_50k_raha_baran_nwcpk_050.log"
    "logs/raha_baran_nwcpk/5_tax_50k_raha_baran_nwcpk_075.log"
    "logs/raha_baran_nwcpk/5_tax_50k_raha_baran_nwcpk_100.log"
    "logs/raha_baran_nwcpk/5_tax_50k_raha_baran_nwcpk_125.log"
    "logs/raha_baran_nwcpk/5_tax_50k_raha_baran_nwcpk_150.log"
    "logs/raha_baran_nwcpk/5_tax_50k_raha_baran_nwcpk_175.log"
    "logs/raha_baran_nwcpk/5_tax_50k_raha_baran_nwcpk_200.log"
    "logs/raha_baran_nwcpk/5_tax_200k_raha_baran_nwcpk_025.log"
    "logs/raha_baran_nwcpk/5_tax_200k_raha_baran_nwcpk_050.log"
    "logs/raha_baran_nwcpk/5_tax_200k_raha_baran_nwcpk_075.log"
    "logs/raha_baran_nwcpk/5_tax_200k_raha_baran_nwcpk_100.log"
    "logs/raha_baran_nwcpk/5_tax_200k_raha_baran_nwcpk_125.log"
    "logs/raha_baran_nwcpk/5_tax_200k_raha_baran_nwcpk_150.log"
    "logs/raha_baran_nwcpk/5_tax_200k_raha_baran_nwcpk_175.log"
    "logs/raha_baran_nwcpk/5_tax_200k_raha_baran_nwcpk_200.log"
    "logs/raha_baran_nwcpk/6_soccer_raha_baran_nwcpk_025.log"
    "logs/raha_baran_nwcpk/6_soccer_raha_baran_nwcpk_050.log"
    "logs/raha_baran_nwcpk/6_soccer_raha_baran_nwcpk_075.log"
    "logs/raha_baran_nwcpk/6_soccer_raha_baran_nwcpk_100.log"
    "logs/raha_baran_nwcpk/6_soccer_raha_baran_nwcpk_125.log"
    "logs/raha_baran_nwcpk/6_soccer_raha_baran_nwcpk_150.log"
    "logs/raha_baran_nwcpk/6_soccer_raha_baran_nwcpk_175.log"
    "logs/raha_baran_nwcpk/6_soccer_raha_baran_nwcpk_200.log"
)

# 创建日志目录
mkdir -p logs/raha_baran_nwcpk

# 逐条执行命令并保存日志
for i in "${!commands[@]}"; do
    echo "Running command for task ${i+1}:"
    echo "${commands[$i]}"
    ${commands[$i]} &> "${log_files[$i]}"
    if [ $? -ne 0 ]; then
        echo "Error: Command failed for task ${i+1}. Check ${log_files[$i]} for details."
        exit 1
    fi
    echo "Task ${i+1} completed successfully. Log saved to: ${log_files[$i]}"
done

echo "All Raha Baran tasks completed successfully."
